# EnvironmentVariableList:
#   Global:
#     AZ_IMAGE_NS: azinternal
#     AZ_IMAGE_PROJ: default
#     AZ_CONTAINER_NS: azinternal
#     AZ_CONTAINER_PROJ: default
#   Project:

version: '3'
services:
  minio1-afs:
    image: minio/minio:RELEASE.2019-04-09T01-22-30Z

    container_name: ${AZ_CONTAINER_NS:-azinternal}-${AZ_CONTAINER_PROJ:-default}-minio1

    volumes:
      - ../minio_data:/data

    environment:
      MINIO_ACCESS_KEY: minioxxxak
      MINIO_SECRET_KEY: minioxxxsk

    command: server /data

  pg-master-afs:
    image: postgres:12

    container_name: ${AZ_CONTAINER_NS:-azinternal}-${AZ_CONTAINER_PROJ:-default}-pg-master-afs
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxx1234
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - "../pgdata:/var/lib/postgresql/data/pgdata"

  graphql-engine-afs:
    image: hasura/graphql-engine:v2.0.0-alpha.3
    container_name: ${AZ_CONTAINER_NS:-azinternal}-${AZ_CONTAINER_PROJ:-default}-hasura-afs
    # restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:xxxx1234@postgres:5432/postgres
      ## HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:xxxx1234@postgres:5432/db_rick_data
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: xxxxhsr
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

    links:
      - "pg-master-afs:postgres"

    depends_on:
      - "pg-master-afs"

  webserver:
    image: ${AZ_IMAGE_NS:-azinternal}/${AZ_IMAGE_PROJ:-default}/webserver-afs
    build:
      context: .

    container_name: ${AZ_CONTAINER_NS:-azinternal}-${AZ_CONTAINER_PROJ:-default}-webserver-afs

    links:
      - "minio1-afs:minio1"
      - "pg-master-afs:postgres"

    depends_on:
      - "minio1-afs"
      - "pg-master-afs"

    environment:
      AFS_SECRETS_FOLDER: "/usr/volumes/share/secrets"

    volumes:
      - ".:/usr/volumes/src/"
      - "../secrets:/usr/volumes/share/secrets"

    command: bash docker-cmd.sh

    # ports:
    #   - "443:443"
    #   - "80:80"

networks:
  default:
    external:
      name: mainginx_net
